// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PCT.BD;

namespace PCT.BD.Migrations
{
    [DbContext(typeof(PCTContext))]
    [Migration("20190203021556_CreatePCTDatabase")]
    partial class CreatePCTDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PCT.Dominio.Concierto", b =>
                {
                    b.Property<int>("IdConcierto")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion");

                    b.Property<string>("Nombre");

                    b.Property<bool>("Publicar");

                    b.Property<string>("UrlPoster");

                    b.HasKey("IdConcierto");

                    b.ToTable("Conciertos");
                });

            modelBuilder.Entity("PCT.Dominio.Galeria", b =>
                {
                    b.Property<int>("IdGaleria")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("IdGaleria");

                    b.ToTable("Galerias");
                });

            modelBuilder.Entity("PCT.Dominio.ItemGaleria", b =>
                {
                    b.Property<int>("IdItemGaleria")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion");

                    b.Property<int?>("GaleriaIdGaleria");

                    b.Property<string>("Link");

                    b.Property<string>("Nombre");

                    b.HasKey("IdItemGaleria");

                    b.HasIndex("GaleriaIdGaleria");

                    b.ToTable("ItemsGaleria");
                });

            modelBuilder.Entity("PCT.Dominio.Musico", b =>
                {
                    b.Property<int>("IdMusico")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido");

                    b.Property<int?>("ConciertoIdConcierto");

                    b.Property<bool>("EsIntegrantePermanente");

                    b.Property<DateTime?>("FechaNacimiento");

                    b.Property<int>("Instrumentos");

                    b.Property<string>("Nombre");

                    b.Property<bool>("Publicar");

                    b.HasKey("IdMusico");

                    b.HasIndex("ConciertoIdConcierto");

                    b.ToTable("Musicos");
                });

            modelBuilder.Entity("PCT.Dominio.ItemGaleria", b =>
                {
                    b.HasOne("PCT.Dominio.Galeria")
                        .WithMany("Items")
                        .HasForeignKey("GaleriaIdGaleria");
                });

            modelBuilder.Entity("PCT.Dominio.Musico", b =>
                {
                    b.HasOne("PCT.Dominio.Concierto")
                        .WithMany("Participantes")
                        .HasForeignKey("ConciertoIdConcierto");
                });
#pragma warning restore 612, 618
        }
    }
}
